SELECT * FROM UNNEST([
  -- ==========================================
  -- UNIVERS : POISSONS BLANCS & NOBLES
  -- ==========================================
  STRUCT('BAR' AS categorie_raw, CAST(NULL AS STRING) AS decoupe, 'POISSON' AS famille_std, 'BAR' AS espece_std),
  STRUCT('BAR DE LIGNE', CAST(NULL AS STRING), 'POISSON', 'BAR'),
  STRUCT('LOUP DE MER', CAST(NULL AS STRING), 'POISSON', 'LOUP'),
  STRUCT('PORTION  DE LOUP DE MER', CAST(NULL AS STRING), 'POISSON', 'LOUP'),  -- ✨ NOUVEAU
  STRUCT('CABILLAUD', CAST(NULL AS STRING), 'POISSON', 'CABILLAUD'),
  STRUCT('ANON', CAST(NULL AS STRING), 'POISSON', 'ANON'),
  STRUCT('DOS', CAST(NULL AS STRING), 'POISSON', 'CABILLAUD'),
  STRUCT('MERLAN', CAST(NULL AS STRING), 'POISSON', 'MERLAN'),
  STRUCT('EGLEFIN', CAST(NULL AS STRING), 'POISSON', 'EGLEFIN'),
  STRUCT('LE HADDOCK', CAST(NULL AS STRING), 'POISSON', 'EGLEFIN'),
  STRUCT('LIEU JAUNE', CAST(NULL AS STRING), 'POISSON', 'LIEU'),
  STRUCT('LIEU NOIR', CAST(NULL AS STRING), 'POISSON', 'LIEU'),
  STRUCT('COLIN', CAST(NULL AS STRING), 'POISSON', 'LIEU'),  -- ✨ NOUVEAU: Colin = Lieu
  STRUCT('LOTTE', CAST(NULL AS STRING), 'POISSON', 'LOTTE'),
  STRUCT('MERLU', CAST(NULL AS STRING), 'POISSON', 'MERLU'),
  STRUCT('MERLUCHON', CAST(NULL AS STRING), 'POISSON', 'MERLU'),  -- ✨ NOUVEAU: Jeune merlu
  STRUCT('MORUE', CAST(NULL AS STRING), 'POISSON', 'MORUE'),
  STRUCT('MORUETTE', CAST(NULL AS STRING), 'POISSON', 'MORUE'),  -- ✨ NOUVEAU: Jeune morue
  STRUCT('SAINT PIERRE', CAST(NULL AS STRING), 'POISSON', 'SAINT_PIERRE'),
  STRUCT('FILET SAINT-PIERRE', CAST(NULL AS STRING), 'POISSON', 'SAINT_PIERRE'),  -- ✨ NOUVEAU
  STRUCT('JULIENNE', CAST(NULL AS STRING), 'POISSON', 'LINGUE'),
  STRUCT('LINGUE', CAST(NULL AS STRING), 'POISSON', 'LINGUE'),
  STRUCT('ELINGUE', CAST(NULL AS STRING), 'POISSON', 'LINGUE'),  -- ✨ NOUVEAU: Variante orthographique
  STRUCT('MAIGRE', CAST(NULL AS STRING), 'POISSON', 'MAIGRE'),
  STRUCT('CONGRE', CAST(NULL AS STRING), 'POISSON', 'CONGRE'),
  STRUCT('VIEILLE', CAST(NULL AS STRING), 'POISSON', 'VIEILLE'),
  STRUCT('TACAUD', CAST(NULL AS STRING), 'POISSON', 'TACAUD'),
  STRUCT('SABRE', CAST(NULL AS STRING), 'POISSON', 'SABRE'),
  STRUCT('SEBASTE', CAST(NULL AS STRING), 'POISSON', 'SEBASTE'),
  STRUCT('BROSME', CAST(NULL AS STRING), 'POISSON', 'BROSME'),  -- ✨ NOUVEAU
  STRUCT('GRENADIER', CAST(NULL AS STRING), 'POISSON', 'GRENADIER'),  -- ✨ NOUVEAU
  STRUCT('MOSTELLE', CAST(NULL AS STRING), 'POISSON', 'MOSTELLE'),  -- ✨ NOUVEAU
  STRUCT('POISSON ENTIER', CAST(NULL AS STRING), 'POISSON', 'POISSON_DIVERS'),
  STRUCT('POISSON', CAST(NULL AS STRING), 'POISSON', 'POISSON_DIVERS'),
  STRUCT('AUTRES POISSONS', CAST(NULL AS STRING), 'POISSON', 'POISSON_DIVERS'),
  STRUCT('POISSONS FILETS', CAST(NULL AS STRING), 'POISSON', 'POISSON_DIVERS'),
  STRUCT('PETIT POISSON', CAST(NULL AS STRING), 'POISSON', 'POISSON_DIVERS'),
  STRUCT('DIVERS', CAST(NULL AS STRING), 'POISSON', 'POISSON_DIVERS'),
  STRUCT('POISSON DE ROCHE', CAST(NULL AS STRING), 'POISSON', 'POISSON_ROCHE'),
  STRUCT('POISSON POUR SOUPE', CAST(NULL AS STRING), 'POISSON', 'POISSON_ROCHE'),  -- ✨ NOUVEAU

  -- ==========================================
  -- UNIVERS : POISSONS PLATS
  -- ==========================================
  STRUCT('SOLE', CAST(NULL AS STRING), 'POISSON', 'SOLE'),
  STRUCT('TURBOT', CAST(NULL AS STRING), 'POISSON', 'TURBOT'),
  STRUCT('BARBUE', CAST(NULL AS STRING), 'POISSON', 'BARBUE'),
  STRUCT('CARRELET', CAST(NULL AS STRING), 'POISSON', 'CARRELET'),
  STRUCT('PLIE', CAST(NULL AS STRING), 'POISSON', 'CARRELET'),
  STRUCT('LIMANDE', CAST(NULL AS STRING), 'POISSON', 'LIMANDE'),
  STRUCT('FLETAN', CAST(NULL AS STRING), 'POISSON', 'FLETAN'),
  STRUCT('PORTIONS FLETAN NOIR', CAST(NULL AS STRING), 'POISSON', 'FLETAN'),  -- ✨ NOUVEAU
  STRUCT('POISSON PLAT', CAST(NULL AS STRING), 'POISSON', 'POISSON_PLAT'),

  -- ==========================================
  -- UNIVERS : DORADES, ROUGETS & RAIES
  -- ==========================================
  STRUCT('DORADE', CAST(NULL AS STRING), 'POISSON', 'DORADE'),
  STRUCT('DORADE GRISE', CAST(NULL AS STRING), 'POISSON', 'DORADE GRISE'),  -- 🔧 FIX: était 'DORADE', maintenant 'DORADE GRISE'
  STRUCT('DORADE PAGRE', CAST(NULL AS STRING), 'POISSON', 'PAGRE'),
  STRUCT('DORADE / PAGRE', CAST(NULL AS STRING), 'POISSON', 'PAGRE'),  -- 🔧 FIX: était 'DORADE', maintenant 'PAGRE'
  STRUCT('PAGEOT', CAST(NULL AS STRING), 'POISSON', 'PAGEOT'),
  STRUCT('PAGRE', CAST(NULL AS STRING), 'POISSON', 'PAGRE'),
  STRUCT('SAR', CAST(NULL AS STRING), 'POISSON', 'SAR'),  -- ✨ NOUVEAU: Poisson méditerranéen
  STRUCT('ROUGET', CAST(NULL AS STRING), 'POISSON', 'ROUGET'),
  STRUCT('ROUGET BARBET', CAST(NULL AS STRING), 'POISSON', 'ROUGET'),
  STRUCT('RAIE', CAST(NULL AS STRING), 'POISSON', 'RAIE'),
  STRUCT('GRONDIN', CAST(NULL AS STRING), 'POISSON', 'GRONDIN'),
  STRUCT('GRONDIN / TOMBE', CAST(NULL AS STRING), 'POISSON', 'GRONDIN'),
  STRUCT('BICHE', CAST(NULL AS STRING), 'POISSON', 'SAUMONETTE'),
  STRUCT('AIGUILLATS', CAST(NULL AS STRING), 'POISSON', 'SAUMONETTE'),
  STRUCT('ROUSSETTE', CAST(NULL AS STRING), 'POISSON', 'SAUMONETTE'),
  STRUCT('SAUMONETTE', CAST(NULL AS STRING), 'POISSON', 'SAUMONETTE'),  -- ✨ NOUVEAU
  STRUCT('REQUIN', CAST(NULL AS STRING), 'POISSON', 'REQUIN'),  -- ✨ NOUVEAU
  STRUCT('RASCASSE', CAST(NULL AS STRING), 'POISSON', 'RASCASSE'),  -- ✨ NOUVEAU
  STRUCT('CHAPON / RASCASSE', CAST(NULL AS STRING), 'POISSON', 'RASCASSE'),  -- ✨ NOUVEAU

  -- ==========================================
  -- UNIVERS : POISSONS BLEUS & EXOTIQUES
  -- ==========================================
  STRUCT('SAUMON', CAST(NULL AS STRING), 'POISSON', 'SAUMON'),
  STRUCT('FILET SAUMON', CAST(NULL AS STRING), 'POISSON', 'SAUMON'),
  STRUCT('DECOUPE SAUMON', CAST(NULL AS STRING), 'POISSON', 'SAUMON'),
  STRUCT('THON', CAST(NULL AS STRING), 'POISSON', 'THON'),
  STRUCT('ESPADON', CAST(NULL AS STRING), 'POISSON', 'ESPADON'),
  STRUCT('MEROU', CAST(NULL AS STRING), 'POISSON', 'MEROU'),
  STRUCT('SARDINE', CAST(NULL AS STRING), 'POISSON', 'SARDINE'),
  STRUCT('MAQUEREAUX', CAST(NULL AS STRING), 'POISSON', 'MAQUEREAU'),
  STRUCT('MAQUEREAU', CAST(NULL AS STRING), 'POISSON', 'MAQUEREAU'),
  STRUCT('LE MAQUEREAU', CAST(NULL AS STRING), 'POISSON', 'MAQUEREAU'),
  STRUCT('HARENG', CAST(NULL AS STRING), 'POISSON', 'HARENG'),
  STRUCT('LE HARENG', CAST(NULL AS STRING), 'POISSON', 'HARENG'),

  -- ANCHOIS : Par défaut = POISSON, mais FILET = EPICERIE
  STRUCT('ANCHOIS', CAST(NULL AS STRING), 'POISSON', 'ANCHOIS'),
  STRUCT('ANCHOIS', 'FILET', 'EPICERIE', 'EPICERIE'),

  STRUCT('CHINCHARD', CAST(NULL AS STRING), 'POISSON', 'CHINCHARD'),
  STRUCT('MULET', CAST(NULL AS STRING), 'POISSON', 'MULET'),
  STRUCT('EPERLAN', CAST(NULL AS STRING), 'POISSON', 'EPERLAN'),  -- ✨ NOUVEAU
  STRUCT('POISSONS BLEUS', CAST(NULL AS STRING), 'POISSON', 'POISSON_BLEU'),
  STRUCT('POISSONS EXOTIQUES', CAST(NULL AS STRING), 'POISSON', 'POISSON_EXOTIQUE'),
  STRUCT('MAHI MAHI', CAST(NULL AS STRING), 'POISSON', 'MAHI_MAHI'),  -- ✨ NOUVEAU: Coryphène
  STRUCT('HOKI', CAST(NULL AS STRING), 'POISSON', 'HOKI'),  -- ✨ NOUVEAU: Poisson blanc
  STRUCT('BADECHE', CAST(NULL AS STRING), 'POISSON', 'BADECHE'),  -- ✨ NOUVEAU
  STRUCT('BARRACUDA', CAST(NULL AS STRING), 'POISSON', 'BARRACUDA'),  -- ✨ NOUVEAU

  -- ==========================================
  -- UNIVERS : EAU DOUCE
  -- ==========================================
  STRUCT('TRUITE', CAST(NULL AS STRING), 'POISSON', 'TRUITE'),
  STRUCT('SANDRE', CAST(NULL AS STRING), 'POISSON', 'SANDRE'),
  STRUCT('BROCHET', CAST(NULL AS STRING), 'POISSON', 'BROCHET'),  -- ✨ NOUVEAU
  STRUCT('OMBLE CHEVALIER', CAST(NULL AS STRING), 'POISSON', 'OMBLE_CHEVALIER'),
  STRUCT('PERCHE DU NIL', CAST(NULL AS STRING), 'POISSON', 'PERCHE'),
  STRUCT('POISSONS D\'EAU DOUCE', CAST(NULL AS STRING), 'POISSON', 'POISSON_EAU_DOUCE'),

  -- ==========================================
  -- UNIVERS : CRUSTACÉS
  -- ==========================================
  STRUCT('CRUSTACES', CAST(NULL AS STRING), 'CRUSTACE', 'CRUSTACE_DIVERS'),
  STRUCT('CREVETTES', CAST(NULL AS STRING), 'CRUSTACE', 'CREVETTE'),
  STRUCT('CREVETTE', CAST(NULL AS STRING), 'CRUSTACE', 'CREVETTE'),  -- ✨ NOUVEAU: Singulier
  STRUCT('GAMBAS FUMEES', CAST(NULL AS STRING), 'CRUSTACE', 'CREVETTE'),
  STRUCT('LANGOUSTINE', CAST(NULL AS STRING), 'CRUSTACE', 'LANGOUSTINE'),
  STRUCT('HOMARD', CAST(NULL AS STRING), 'CRUSTACE', 'HOMARD'),
  STRUCT('VIVIERS', CAST(NULL AS STRING), 'CRUSTACE', 'HOMARD'),
  STRUCT('TOURTEAU', CAST(NULL AS STRING), 'CRUSTACE', 'TOURTEAU'),
  STRUCT('TOURTEAUX - ARAIGNEES', CAST(NULL AS STRING), 'CRUSTACE', 'TOURTEAU'),  -- ✨ NOUVEAU: Mix de crustacés
  STRUCT('PINCE DE CRABE CUIT', CAST(NULL AS STRING), 'CRUSTACE', 'TOURTEAU'),
  STRUCT('CHAIR DE CRABE', CAST(NULL AS STRING), 'CRUSTACE', 'CRABE'),
  STRUCT('CRABE', CAST(NULL AS STRING), 'CRUSTACE', 'CRABE'),  -- ✨ NOUVEAU
  STRUCT('KING CRAB', CAST(NULL AS STRING), 'CRUSTACE', 'CRABE'),  -- ✨ NOUVEAU: Crabe royal
  STRUCT('ETRILLE', CAST(NULL AS STRING), 'CRUSTACE', 'ETRILLE'),  -- ✨ NOUVEAU: Petit crabe
  STRUCT('ARAIGNEE', CAST(NULL AS STRING), 'CRUSTACE', 'ARAIGNEE'),  -- ✨ NOUVEAU
  STRUCT('LANGOUSTE', CAST(NULL AS STRING), 'CRUSTACE', 'LANGOUSTE'),
  STRUCT('QUEUE LANGOUSTE CRUE', CAST(NULL AS STRING), 'CRUSTACE', 'LANGOUSTE'),
  STRUCT('POUCE PIED', CAST(NULL AS STRING), 'CRUSTACE', 'POUCE_PIED'),  -- ✨ NOUVEAU
  STRUCT('GRENOUILLES', CAST(NULL AS STRING), 'DIVERS', 'GRENOUILLE'),
  STRUCT('CUISSES DE GRENOUILLE', CAST(NULL AS STRING), 'DIVERS', 'GRENOUILLE'),

  -- ==========================================
  -- UNIVERS : COQUILLAGES & CÉPHALOPODES
  -- ==========================================
  STRUCT('HUITRE', CAST(NULL AS STRING), 'COQUILLAGE', 'HUITRE'),
  STRUCT('HUITRES', CAST(NULL AS STRING), 'COQUILLAGE', 'HUITRE'),
  STRUCT('LA FAMILLE BOUTRAIS', CAST(NULL AS STRING), 'COQUILLAGE', 'HUITRE'),
  STRUCT('BIO DE BRETAGNE HENRY', CAST(NULL AS STRING), 'COQUILLAGE', 'HUITRE'),
  STRUCT('MOULES', CAST(NULL AS STRING), 'COQUILLAGE', 'MOULE'),
  STRUCT('COQUILLAGES', CAST(NULL AS STRING), 'COQUILLAGE', 'COQUILLAGE_DIVERS'),
  STRUCT('COQUILLE ST JACQUES', CAST(NULL AS STRING), 'COQUILLAGE', 'SAINT_JACQUES'),
  STRUCT('NOIX ST JACQUES', CAST(NULL AS STRING), 'COQUILLAGE', 'SAINT_JACQUES'),
  -- ✨ NOUVEAUX COQUILLAGES
  STRUCT('PALOURDE', CAST(NULL AS STRING), 'COQUILLAGE', 'PALOURDE'),
  STRUCT('PRAIRE', CAST(NULL AS STRING), 'COQUILLAGE', 'PRAIRE'),
  STRUCT('BULOT', CAST(NULL AS STRING), 'COQUILLAGE', 'BULOT'),
  STRUCT('VERNIS', CAST(NULL AS STRING), 'COQUILLAGE', 'VERNIS'),
  STRUCT('BIGORNEAU', CAST(NULL AS STRING), 'COQUILLAGE', 'BIGORNEAU'),
  STRUCT('COUTEAU', CAST(NULL AS STRING), 'COQUILLAGE', 'COUTEAU'),
  STRUCT('COQUE', CAST(NULL AS STRING), 'COQUILLAGE', 'COQUE'),
  STRUCT('ORMEAU', CAST(NULL AS STRING), 'COQUILLAGE', 'ORMEAU'),
  STRUCT('CLAM', CAST(NULL AS STRING), 'COQUILLAGE', 'CLAM'),
  STRUCT('AMANDE', CAST(NULL AS STRING), 'COQUILLAGE', 'AMANDE'),
  STRUCT('TELLINE', CAST(NULL AS STRING), 'COQUILLAGE', 'TELLINE'),
  STRUCT('VENUS', CAST(NULL AS STRING), 'COQUILLAGE', 'VENUS'),
  -- ✨ CÉPHALOPODES
  STRUCT('ENCORNET', CAST(NULL AS STRING), 'CEPHALOPODE', 'ENCORNET'),
  STRUCT('CEPHALOPODES', CAST(NULL AS STRING), 'CEPHALOPODE', 'ENCORNET'),
  STRUCT('SEICHE', CAST(NULL AS STRING), 'CEPHALOPODE', 'SEICHE'),
  STRUCT('POULPE', CAST(NULL AS STRING), 'CEPHALOPODE', 'POULPE'),

  -- ==========================================
  -- UNIVERS : DIVERS
  -- ==========================================
  STRUCT('OURSIN', CAST(NULL AS STRING), 'DIVERS', 'OURSIN'),  -- ✨ NOUVEAU: Échinoderme

  -- ==========================================
  -- UNIVERS : TRAITEUR, EPICERIE & ELABORES
  -- ==========================================
  STRUCT('AIDE CULINAIRES', CAST(NULL AS STRING), 'EPICERIE', 'EPICERIE'),
  STRUCT('LES SAUCES', CAST(NULL AS STRING), 'TRAITEUR', 'SAUCE'),
  STRUCT('SAUCES SPECIALES POISSON', CAST(NULL AS STRING), 'TRAITEUR', 'SAUCE'),
  STRUCT('EPICERIE FINE', CAST(NULL AS STRING), 'EPICERIE', 'EPICERIE'),
  STRUCT('BLINIS', CAST(NULL AS STRING), 'EPICERIE', 'EPICERIE'),
  STRUCT('TARAMAS', CAST(NULL AS STRING), 'TRAITEUR', 'TARAMA'),
  STRUCT('LES ŒUFS DE POISSON', CAST(NULL AS STRING), 'TRAITEUR', 'OEUFS_POISSON'),
  STRUCT('ŒUFS DE POISSON', CAST(NULL AS STRING), 'TRAITEUR', 'OEUFS_POISSON'),
  STRUCT('PERLES DE SAVEUR', CAST(NULL AS STRING), 'TRAITEUR', 'OEUFS_POISSON'),
  STRUCT('HARENGA', CAST(NULL AS STRING), 'TRAITEUR', 'EPICERIE'),
  STRUCT('MARINADE', CAST(NULL AS STRING), 'EPICERIE', 'EPICERIE'),
  STRUCT('SALADES', CAST(NULL AS STRING), 'EPICERIE', 'EPICERIE'),
  STRUCT('TARTINABLES', CAST(NULL AS STRING), 'EPICERIE', 'EPICERIE'),
  STRUCT('LES PLATS CUISINES', CAST(NULL AS STRING), 'EPICERIE', 'EPICERIE'),
  STRUCT('PLATS CUISINES', CAST(NULL AS STRING), 'EPICERIE', 'EPICERIE'),
  STRUCT('PRODUITS ELABORES', CAST(NULL AS STRING), 'EPICERIE', 'EPICERIE'),
  STRUCT('QUENELLES', CAST(NULL AS STRING), 'EPICERIE', 'EPICERIE'),
  STRUCT('SAUMURE', CAST(NULL AS STRING), 'EPICERIE', 'EPICERIE'),
  STRUCT('POISSONS PANES FRAIS', CAST(NULL AS STRING), 'EPICERIE', 'EPICERIE'),
  STRUCT('LES TERRINES MARINES', CAST(NULL AS STRING), 'EPICERIE', 'EPICERIE'),
  STRUCT('SAURISSERIE TRADITIONNELLE', CAST(NULL AS STRING), 'TRAITEUR', 'FUME'),
  STRUCT('FLETAN FUME', CAST(NULL AS STRING), 'TRAITEUR', 'FUME'),
  STRUCT('SOUPES', CAST(NULL AS STRING), 'TRAITEUR', 'SOUPE'),
  STRUCT('SOUPE HENNEQUIN "MAISON"', CAST(NULL AS STRING), 'TRAITEUR', 'SOUPE'),
  STRUCT('ALGUES COMESTIBLES', CAST(NULL AS STRING), 'DIVERS', 'ALGUES'),

  -- ==========================================
  -- CAS SPECIFIQUES (BRUTS)
  -- ==========================================
  STRUCT('**PRODUITS SURGELES QUALITE PREMIUM**', CAST(NULL AS STRING), 'SURGELE', 'CEPHALOPODE'),
  STRUCT('COUPE " FAIT MAISON "', CAST(NULL AS STRING), 'POISSON', 'POISSON_DIVERS'),
  STRUCT('CUISSON', CAST(NULL AS STRING), 'CRUSTACE', 'CRUSTACE_DIVERS'),
  STRUCT('ROLLMOPS "LA BARRE"', CAST(NULL AS STRING), 'TRAITEUR', 'FUME'),
  STRUCT('', CAST(NULL AS STRING), 'NON_DEFINI', 'NON_DEFINI')
])
